[2023-05-08T09:55:29.057+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T09:54:55.626225+00:00 [queued]>
[2023-05-08T09:55:29.065+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T09:54:55.626225+00:00 [queued]>
[2023-05-08T09:55:29.066+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-08T09:55:29.082+0000] {taskinstance.py:1350} INFO - Executing <Task(SparkSubmitOperator): spark_load_stock_data> on 2023-05-08 09:54:55.626225+00:00
[2023-05-08T09:55:29.086+0000] {standard_task_runner.py:57} INFO - Started process 342 to run task
[2023-05-08T09:55:29.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'upload_to_gcs', 'spark_load_stock_data', 'manual__2023-05-08T09:54:55.626225+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmp7vid6571']
[2023-05-08T09:55:29.090+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask spark_load_stock_data
[2023-05-08T09:55:29.134+0000] {task_command.py:410} INFO - Running <TaskInstance: upload_to_gcs.spark_load_stock_data manual__2023-05-08T09:54:55.626225+00:00 [running]> on host e1ef748a539e
[2023-05-08T09:55:29.200+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_gcs' AIRFLOW_CTX_TASK_ID='spark_load_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T09:54:55.626225+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T09:54:55.626225+00:00'
[2023-05-08T09:55:29.208+0000] {spark_submit.py:204} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-05-08T09:55:29.209+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 391, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 335, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 247, in _mask_cmd
    ' '.join(connection_cmd),
TypeError: sequence item 8: expected str instance, int found
[2023-05-08T09:55:29.215+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=upload_to_gcs, task_id=spark_load_stock_data, execution_date=20230508T095455, start_date=20230508T095529, end_date=20230508T095529
[2023-05-08T09:55:29.229+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task spark_load_stock_data (sequence item 8: expected str instance, int found; 342)
[2023-05-08T09:55:29.261+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T09:55:29.308+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
